package prelims.UserInterface;

import prelims.TextAreaOutputStream;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.io.*;
import java.util.Scanner;

public class AccountManagement extends JFrame {

    // Variables declaration - do not modify
    private javax.swing.JTextArea AccountManagementTextArea;
    private javax.swing.JButton Cancel;
    private javax.swing.JTextField NewFirstnameTF;
    private javax.swing.JTextField NewName;
    private javax.swing.JTextField NewPasswordTF;
    private javax.swing.JTextField NewUsernameTF;
    private javax.swing.JTextField ReNewPasswordTF;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;

    public static String username = SignInWindowUI.username;
    private Scanner x;
    public String password;
    public String fullname;
    public String display;

    String path = "res\\Accounts.csv";
    // End of variables declaration

    /**
     * Creates new form AccountManagement
     */
    public AccountManagement() {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | UnsupportedLookAndFeelException | IllegalAccessException | InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        initComponents();

        try(
                BufferedReader br = new BufferedReader(new FileReader(path));
        ){
            String currentLine = br.readLine();

            while(currentLine != null){
                String[] data = currentLine.split(",");

                if(data[2].equals(username)){
                    fullname = data[1];
                    username = data[2];
                    password = data[3];
                }
                currentLine = br.readLine();
            }

            display = "Fullname: " + fullname + "\nUsername: " + username + "\nPassword: " + password;
            AccountManagementTextArea.setText(display);

        }
        catch (IOException e){
            e.printStackTrace();
        }


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AccountManagementTextArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NewFirstnameTF = new javax.swing.JTextField();
        NewName = new javax.swing.JTextField();
        NewUsernameTF = new javax.swing.JTextField();
        NewPasswordTF = new javax.swing.JTextField();
        ReNewPasswordTF = new javax.swing.JTextField();
        Cancel = new javax.swing.JButton();
        Submit = new javax.swing.JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("ACCOUNT MANAGEMENT");

        jLabel2.setText("New First Name:");

        jLabel3.setText("New Full Name");

        AccountManagementTextArea.setColumns(20);
        AccountManagementTextArea.setRows(5);
        jScrollPane1.setViewportView(AccountManagementTextArea);

        jLabel4.setText("New Username:");

        jLabel5.setText("New Password:");

        jLabel6.setText("Retype New Password:");

        Cancel.setText("CANCEL");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        Submit.setText("SUBMIT");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(90, 90, 90)
                                                .addComponent(jLabel1))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(Cancel)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel2)
                                                                .addComponent(jLabel3)
                                                                .addComponent(jLabel4)
                                                                .addComponent(jLabel5)
                                                                .addComponent(jLabel6)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(24, 24, 24)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(NewFirstnameTF)
                                                                        .addComponent(NewName)
                                                                        .addComponent(NewUsernameTF)
                                                                        .addComponent(NewPasswordTF)
                                                                        .addComponent(ReNewPasswordTF, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(87, 87, 87)
                                                                .addComponent(Submit)))))
                                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(NewFirstnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(NewName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(NewUsernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(NewPasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(ReNewPasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Cancel)
                                        .addComponent(Submit))
                                .addContainerGap())
        );
        setResizable(false);
        AccountManagementTextArea.setEditable(false);
        NewFirstnameTF.setVisible(false);
        jLabel2.setVisible(false);
        pack();
        setLocationRelativeTo(null);
    }

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.dispose();
    }

    private void SubmitActionPerformed(ActionEvent evt){
        String newName = NewName.getText();
        String newUsername = NewUsernameTF.getText();
        String newPassword = NewPasswordTF.getText();

        editLine(path, username, newName, newUsername, newPassword);

        JOptionPane.showMessageDialog(null, "Successfully updated Credentials, Logged out, Please Log In Again.", "Success!", JOptionPane.INFORMATION_MESSAGE);
        System.exit(0);
    }

    private void editLine(String file, String findUsername, String newName, String newUsername, String newPassword){
        String tempfile = "res\\temp.csv";
        File oldfile = new File(file);
        File newFile = new File(tempfile);

        String newFilename = "res\\Accounts.csv";
        File newFilename_ = new File(newFilename);

        String line = "";
        int counter = 1;

        try{
            BufferedReader br = new BufferedReader(new FileReader(oldfile));
            BufferedWriter writer = new BufferedWriter(new FileWriter(newFile));

            while((line = br.readLine()) != null){
                String[] values = line.split(",");

                if(values[2].equals(findUsername)){
                    continue;
                }

                writer.write(line + System.getProperty("line.separator"));
                counter++;
            }

            writer.write(counter+","+newName+","+newUsername+","+newPassword);

            writer.close();
            br.close();

        }catch(Exception e){
            e.printStackTrace();
        }

        boolean b = oldfile.delete();
        boolean a = newFile.renameTo(newFilename_);
    }

}
